services:
  db:
    image: mysql:8.0
    container_name: api_gestao_db
    restart: always
    env_file:
      - .env
    command: >
      --innodb-buffer-pool-size=256M
      --max-connections=60
    volumes:
      - db_data:/var/lib/mysql
    deploy: {}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p@Davila147 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: apigestao_web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JAVA_OPTS: -Xms512m -Xmx900m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+AlwaysPreTouch
    ports:
      - "8081:8081"